### ISSUE TITLE
Performance evaluation benchmark

### ISSUE THREAD

**Issue by Leerw** [HFAiLab/ffrecord#2]
Hi, thanks for your kind work! Is there any benchmark of performance available?

**Comment by Leerw** [comment]
installation failed as well

**Comment by KinglittleQ** [comment]
There is a benchmark in https://github.com/HFAiLab/ffrecord/blob/main/benchs/bench_dataloader.py.
![ffdata](https://user-images.githubusercontent.com/26847868/145740616-9b79f58b-cc93-429b-bb6e-3b199e6c19d9.png)


To install ffrecord, please try `python setup.py install`.
