### ISSUE TITLE
Error of "RuntimeError: 'ns > 0' failed. Number of submitted requests: -22"

### ISSUE THREAD

**Issue by xlxwalex** [HFAiLab/ffrecord#4]
I apply the sample code from README,  but an error occurred in `data = self.reader.read(indices)` of the `__getitem__` method in ffrecord.torch.dataset module. The following are more detailed error messages:

---------------------
```
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "xxxx/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "xxxx.py", line 172, in worker
    trainer.train(args, gpu_id, rank, train_loader, model, optimizer, scheduler, train_sampler)
  File "xxxx.py", line 39, in train
    for step, batch in enumerate(loader):
  File "xxxx/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "xxxx/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "xxxx/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "xxxx/python3.8/site-packages/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "xxxx/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "xxxx/python3.8/site-packages/ffrecord-1.3.2+35c6863-py3.8-linux-x86_64.egg/ffrecord/torch/dataloader.py", line 151, in fetch
    data = self.dataset[indexes]
  File "xxx.py", line 34, in __getitem__
    data = self.reader.read(indices)
RuntimeError: 'ns > 0' failed. Number of submitted requests: -22
Error in std::vector<ffrecord::MemBlock> ffrecord::FileReader::read_batch(const std::vector<long int>&) at xxx/ffrecord/ffrecord/src/reader.cpp line 225
```
---------------
What might be the cause of this error?

**Comment by KinglittleQ** [comment]
Could you see the same error if you rerun the code?

**Comment by xlxwalex** [comment]
Yeah, i encountered this error every time in distributed training. Also, I just tried using a single GPU and it doesn't seem to stuck with this error. Could this be caused by the distributed sampler?

**Comment by KinglittleQ** [comment]
Thanks for your report. Could you please provide a minimal self-contained example to reproduce this problem?

**Comment by xlxwalex** [comment]
I'll try to package a small dataset with the script to reproduce the problem.

**Comment by xlxwalex** [comment]
Hi, when I was trying to reproduce the error with minimal example, I found that the error was due to the `num_workers` setting of the DataLoader.  [ffrecord_Error](https://colab.research.google.com/drive/1CT5eXH8t7HMm53kmjPdxv49DfJITjEq_?usp=sharing) is an example that can be used for reproduction. 

If I do not specify the `num_workers`, the program will not report the errors, and I am not sure if this is a problem with the way I use.

**Comment by KinglittleQ** [comment]
Thanks! I will investigate it.

**Comment by YOUSIKI** [comment]
Hi. I just run into the same issue. As for my code, any num_workers >= 16  results the RuntimeError, and num_workers < 16 (including 0) is fine. And the returned errno of `io_submit` is always `-22`, which stands for invalid argument.

**Comment by ddebby** [comment]
same issue when num_workers >13 in my case.

**Comment by sphish** [comment]
Maybe you can try setting aio_max_nr to a larger value. https://sort.veritas.com/public/documents/HSO/2.0/linux/productguides/html/hfo_admin_rhel/ch04s03.htm
